### ISSUE TITLE
Not release v0.1.1？

### ISSUE THREAD

**Issue by ksss** [condor/ltsv#6]
I found a git tag [v0.1.1](https://github.com/condor/ltsv/releases/tag/v0.1.1).
But I cannot found v0.1.1 in rubygems.
https://rubygems.org/gems/ltsv/versions

**Comment by a-suenami** [comment]
I have same problem :cry:

**Comment by condor** [comment]
I have discarded the tag v0.1.1 since the version is not released.

The next version will be v0.2.0 since some specification will be changed.

**Comment by a-suenami** [comment]
Thanks for your reply.
I will wait to release v0.2.0.

**Comment by ujihisa** [comment]
The current latest 0.1.0 still doesn't have the latest change at `parse_line`. For about 2 years. When will either 0.2.0 or 0.1.1 be released?

**Comment by condor** [comment]
v0.1.2 is released today! (v0.1.1 has become a retired number.)

**Comment by ujihisa** [comment]
yay!
